# Find VIPERS includes and library
#
# This module defines
#  VIPERS_FOUND        - True if VIPERS is found
#  VIPERS_INCLUDE_DIR  - Where to find VIPERS.hpp, etc.
#  VIPERS_LIBRARIES    - Libraries needed to link to VIPERS
#

IF(VIPERS_FOUND)
  # Already in cache, be silent
  SET(VIPERS_FIND_QUIETLY TRUE)
ENDIF()

SET(VIPERS_POSSIBLE_DIRS "${VIPERS_ROOT_DIR}" "$ENV{VIPERS_ROOT_DIR}" "/usr/local" "/usr")
SET(VIPERS_NAMES vipers libvipers)

FIND_PATH(VIPERS_INCLUDE_DIR NAMES "VIPERS.hpp" PATHS ${VIPERS_POSSIBLE_DIRS})
FIND_LIBRARY(VIPERS_LIBRARY NAMES ${VIPERS_NAMES} PATHS ${VIPERS_POSSIBLE_DIRS} PATH_SUFFIXES include include/VIPERS) 

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(VIPERS DEFAULT_MSG VIPERS_LIBRARY VIPERS_INCLUDE_DIR)

IF(VIPERS_FOUND)
  SET(VIPERS_LIBRARIES ${VIPERS_LIBRARY})
ENDIF()

MARK_AS_ADVANCED(VIPERS_LIBRARY VIPERS_INCLUDE_DIR)
